routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::resource('products', 'ProductController', ['except' => ['show']])->middleware('auth');

Route::middleware(['auth'])->group(function() {
	Route::get('/', 'ProductController@index');
	Route::get('products/{product}/transactions/create', 'TransactionController@create')->name('transactions.create');
	Route::post('products/{product}/transactions', 'TransactionController@store')->name('transactions.store');
	Route::get('products/{product}/transactions', 'TransactionController@index')->name('transactions.index');
	Route::get('products/search', 'ProductController@search')->name('products.search');
	Route::get('products/export', 'ProductController@export')->name('products.export');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Transaction;

class Product extends Model
{
    
	protected $fillable = ['nombre', 'mark', 'description', 'quantity'];

    public function transactions() {
    	return $this->hasMany(Transaction::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $products = Product::orderBy('nombre', 'desc')->paginate(10);
        return view('products.list', ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nombre' => 'required|unique:products',
            'mark' => 'required',
            'description' => 'nullable',
            'quantity' => 'required|integer|min:0' 
        ]);

        $product = new Product;
        $product->nombre = $request->nombre;
        $product->mark = $request->mark;
        $product->description = $request->description;
        $product->quantity = $request->quantity;
        $product->save();

        session()->flash('message', 'Producto agregado con éxito');
        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product) {       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product) {
        return view('products.change', ['product' => $product]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product) {
        $this->validate($request, [
            'nombre' => 'required',
            'mark' => 'required',
            'description' => 'nullable'
        ]);

        $product->nombre = $request->nombre;
        $product->mark = $request->mark;
        $product->description = $request->description;
        $product->save();
        session()->flash('message', 'Producto actualizado con éxito');
        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product) {
        $product->delete();

        session()->flash('message', 'Producto eliminado con éxito');
        return redirect()->route('products.index');
    }

    
    public function search(Request $request) {
        $products = Product::where('nombre', 'like', '%'.$request->s.'%')
                             ->orWhere('mark', 'like', '%'.$request->s.'%')
                             ->orWhere('description', 'like', '%'.$request->s.'%')
                             ->paginate(10);
        return view('products.list', ['products' => $products]);
    }


    public function export(Request $request) {
        Excel::create('inventario_reisa', function($excel) {
            
            $excel->setTitle('Inventario Reisa');

            $excel->setCreator('Sergio Durán')
                  ->setCompany('Reisa Tecnología');

            $excel->setDescription('Listado de productos dentro del stock de Reisa');
            
            $excel->getDefaultStyle()
                  ->getAlignment()
                  ->setHorizontal(\PHPExcel_Style_Alignment::HORIZONTAL_LEFT)
                  ->setVertical(\PHPExcel_Style_Alignment::VERTICAL_CENTER);

            $excel->sheet('Inventario', function($sheet) {
                $products = Product::all(['nombre', 'mark', 'description', 'quantity', 'created_at']);
                $sheet->fromModel($products);

                $sheet->cells('A1:E1', function($cells) {
                    $cells->setBackground('#42a5f5');
                    $cells->setfontColor('#FFFFFF');
                    $cells->setfontSize(16);
                    $cells->setAlignment('center');
                     $cells->setValignment('center');
                });

                $sheet->cell('A1', function($cell) {
                    $cell->setValue('Código de producto');
                });

                $sheet->cell('B1', function($cell) {
                    $cell->setValue('Marca');
                });
                $sheet->cell('C1', function($cell) {
                    $cell->setValue('Descripción');
                });
                $sheet->cell('D1', function($cell) {
                    $cell->setValue('Cantidad en stock');
                });
                $sheet->cell('E1', function($cell) {
                    $cell->setValue('Fecha de registro');
                });
                $sheet->setHeight(1, 20);

                for($i = 1; $i <= count($products) + 1; $i++) {
                    $sheet->setHeight($i, 20);
                }

                $sheet->setColumnFormat(array(
                    'E' => 'dd/mm/yy',
                ));

                $sheet->setAutoSize(true);
            });


        })->download('xlsx');
    } 
}

resources/views/products/change.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<h2>Editar producto</h2>
		<div class="row">
			<form action="{{ route('products.update', ['product' => $product->id]) }}" method="POST">
				{{ csrf_field() }}
				<input type="hidden" name="_method" value="PUT">
				<div class="input-field col s8">
					<input type="text" name="nombre" value="{{ $product->nombre or old('nombre') }}" class="validate" required autofocus>
					<label for="nombre">Código de producto</label>
				</div>

				<div class="input-field col s8">
					<input type="text" name="mark" value="{{ $product->mark or old('mark') }}" class="validate" required>
					<label for="mark">Marca del producto</label>
				</div>

				<div class="input-field col s8">
					<textarea name="description" id="description" class="materialize-textarea">{{$product->description or old('description')}}</textarea>
					<label for="description">Descripción</label>
				</div>

				<div class="input-field col s8">
					<button type="submit" class="waves-effect waves-light btn">
						Actualizar producto
						<i class="material-icons right">send</i>
					</button>
				</div>
			</form>
		</div>
	</div>

@endsection

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<h2>Crear nuevo producto</h2>
		<div class="row">
			<form action="{{ route('products.store') }}" method="POST">
				{{ csrf_field() }}
				<div class="input-field col s8">
					<input type="text" name="nombre" value="{{ old('nombre') }}" class="validate" required autofocus>
					<label for="nombre">Código de producto</label>
					@if ($errors->has('nombre'))
                        <div class="card-panel red">
                            <span class="white-text">
                                {{$errors->first('nombre')}}
                            </span>
                        </div>
                    @endif
				</div>

				<div class="input-field col s8">
					<input type="text" name="mark" value="{{ old('mark') }}" class="validate" required>
					<label for="mark">Marca del producto</label>
				</div>

				<div class="input-field col s8">
					<textarea name="description" id="description" class="materialize-textarea"></textarea>
					<label for="description">Descripción</label>
				</div>

				<div class="input-field col s8">
					<input type="number" name="quantity" value="{{ old('quantity') }}" class="validate" min="0" required>
					<label for="quantity">Cantidad en inventario</label>
				</div>

				<div class="input-field col s8">
					<button type="submit" class="waves-effect waves-light btn">
						Guardar producto
						<i class="material-icons right">send</i>
					</button>
				</div>
			</form>
		</div>
	</div>

@endsection

resources/views/products/list.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<h2>Listado de productos</h2>

		<div class="row">
			<table class="centered responsive-table striped">
				<thead>
					<tr>
						<th>Código de Producto</th>
						<th>Marca</th>
						<th>Descripción</th>
						<th>Inventario</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>
					@foreach ($products as $product)
						<tr>
							<td>{{ $product->nombre }}</td>
							<td>{{ $product->mark }}</td>
							<td>{{ $product->description }}</td>
							<td>{{ $product->quantity }}</td>
							<td>
								<a href="{{ route('products.edit', ['product' => $product->id]) }}" class="tooltipped amber-text" data-position="right" data-delay="30" data-tooltip="Editar producto"><i class="material-icons">edit</i></a>
								<a href="{{ route('transactions.create', ['product' => $product->id]) }}" class="tooltipped green-text" data-position="right" data-delay="30" data-tooltip="Modificar inventario"><i class="material-icons">sync</i></a>
								<a href="{{ route('transactions.index', ['product' => $product->id]) }}" class="tooltipped blue-text" data-position="right" data-delay="30" data-tooltip="Historico del producto"><i class="material-icons">history</i></a>
								<form action="{{ route('products.destroy', ['product' => $product->id])}}" method="POST" style="display: inline-block;">
									{{ csrf_field() }}
									<input type="hidden" name="_method" value="DELETE">
									<a href="#" onclick="this.parentNode.submit();" class="tooltipped red-text" data-position="right" data-delay="30" data-tooltip="Eliminar producto"><i class="material-icons">delete</i></a>
								</form>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
	
	<div class="row center-align">
		{{$products->links()}}
	</div>


	<div class="fixed-action-btn">
		<a href="{{ route('products.export') }}" target="_blank" class="tooltipped btn-floating btn-large red lighten-1" data-position="left" data-tooltip="Exportar a excel">
			<i class="large material-icons">file_download</i>
		</a>
		<a href="{{ route('products.create') }}" class="tooltipped btn-floating btn-large blue" data-position="left" data-tooltip="Agregar producto">
			<i class="large material-icons">add</i>
		</a>
	</div>
@endsection

@section('mini_scripts')
	@if(session('message'))
        <script>
            Materialize.toast('{{ session("message") }}', 4000, 'teal lighten-2 white-text');
        </script>
    @endif
@endsection